
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.image.BandCombineOp;
import java.io.IOException;
import java.io.StringReader;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;


import java.util.Iterator;
import java.util.Set;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class MainFrame extends javax.swing.JFrame {
    DB_MAN DBM = new DB_MAN();
    String loginID = null;
   
 
    //key들을 넣을 배열들
    ArrayList description = new ArrayList();//회차   
    ArrayList docexamdt = new ArrayList();
    ArrayList docpassdt = new ArrayList();
    ArrayList docregenddt = new ArrayList();
    ArrayList docregstartdt = new ArrayList();
    ArrayList docsubmitentdt = new ArrayList();
    ArrayList docsubmitstartdt = new ArrayList();
    ArrayList pracexamenddt = new ArrayList();
    ArrayList pracexamstartdt = new ArrayList();
    ArrayList pracpassdt = new ArrayList();
    ArrayList pracregenddt = new ArrayList();
    ArrayList pracregstartdt = new ArrayList();
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        btnLLogin = new javax.swing.JButton();
        btnLJoin = new javax.swing.JButton();
        txtLID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLPW = new javax.swing.JPasswordField();
        jFrame2 = new javax.swing.JFrame();
        lblID = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnJoin = new javax.swing.JButton();
        checkResult = new javax.swing.JLabel();
        lblPw = new javax.swing.JLabel();
        lblPwCheck = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtJID = new javax.swing.JTextField();
        btnIdCheck = new javax.swing.JButton();
        txtJCheckPW = new javax.swing.JPasswordField();
        txtJPW = new javax.swing.JPasswordField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        checkPattern = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnLogin = new javax.swing.JButton();
        lblLoginCheck = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        btnLLogin.setFont(new java.awt.Font("굴림", 0, 20)); // NOI18N
        btnLLogin.setText("로 그 인");
        btnLLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLLoginActionPerformed(evt);
            }
        });

        btnLJoin.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        btnLJoin.setText("회원가입");
        btnLJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLJoinActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("굴림", 0, 20)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("굴림", 0, 20)); // NOI18N
        jLabel2.setText("PW");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLID, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtLPW))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLJoin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGap(0, 9, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addComponent(txtLPW)))
                    .addComponent(btnLLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(btnLJoin)
                .addGap(54, 54, 54))
        );

        lblID.setFont(new java.awt.Font("굴림", 0, 20)); // NOI18N
        lblID.setText("아이디");

        btnJoin.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        btnJoin.setText("회원 가입");
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });

        checkResult.setFont(new java.awt.Font("돋움", 0, 14)); // NOI18N
        checkResult.setForeground(new java.awt.Color(102, 102, 255));
        checkResult.setText("아이디 중복을 확인해주세요.");

        lblPw.setFont(new java.awt.Font("굴림", 0, 20)); // NOI18N
        lblPw.setText("비밀번호");

        lblPwCheck.setFont(new java.awt.Font("굴림", 0, 20)); // NOI18N
        lblPwCheck.setText("비밀번호 확인");

        lblName.setFont(new java.awt.Font("굴림", 0, 20)); // NOI18N
        lblName.setText("성명");

        txtJID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJIDKeyTyped(evt);
            }
        });

        btnIdCheck.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        btnIdCheck.setText("중복 확인");
        btnIdCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdCheckActionPerformed(evt);
            }
        });

        txtJPW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJPWKeyTyped(evt);
            }
        });

        lblPhone.setFont(new java.awt.Font("굴림", 0, 20)); // NOI18N
        lblPhone.setText("전화번호");

        checkPattern.setFont(new java.awt.Font("돋움", 0, 14)); // NOI18N
        checkPattern.setForeground(new java.awt.Color(102, 102, 255));
        checkPattern.setText("영문 소문자, 숫자, 특수문자 조합, 8~15자리까지");

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame2Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jFrame2Layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkResult)
                                    .addGroup(jFrame2Layout.createSequentialGroup()
                                        .addComponent(txtJID, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnIdCheck))))
                            .addComponent(lblID))
                        .addGap(58, 58, 58))
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jFrame2Layout.createSequentialGroup()
                                        .addComponent(lblPhone)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jFrame2Layout.createSequentialGroup()
                                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblName)
                                            .addComponent(lblPwCheck))
                                        .addGap(31, 31, 31)
                                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtJCheckPW)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame2Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(jFrame2Layout.createSequentialGroup()
                                    .addGap(196, 196, 196)
                                    .addComponent(btnJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jFrame2Layout.createSequentialGroup()
                                .addComponent(lblPw)
                                .addGap(78, 78, 78)
                                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkPattern)
                                    .addComponent(txtJPW, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtJID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIdCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPw)
                    .addComponent(txtJPW, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(checkPattern)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPwCheck)
                    .addComponent(txtJCheckPW, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "기능사", "기사, 산업기사", "기능장", "기술사" }));

        btnSearch.setFont(new java.awt.Font("굴림", 0, 20)); // NOI18N
        btnSearch.setText("조    회");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("굴림", 0, 20)); // NOI18N
        btnSave.setText("저    장");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "년도별/회 별", "필기시험 원서접수", "필기시험", "필기시험 합격자 발표", "응시자격 서류제출", "실기시험 원서접수", "실기시험", "최종 합격자 발표"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(60);
        jScrollPane1.setViewportView(jTable1);

        btnLogin.setFont(new java.awt.Font("굴림", 0, 20)); // NOI18N
        btnLogin.setText("로 그 인");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblLoginCheck.setFont(new java.awt.Font("돋움", 0, 30)); // NOI18N
        lblLoginCheck.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1324, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblLoginCheck))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLoginCheck)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("자격증 일정보기", jPanel1);

        btnDelete.setFont(new java.awt.Font("굴림", 0, 20)); // NOI18N
        btnDelete.setText("삭    제");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "년도별/회 별", "필기시험 원서접수", "필기시험", "필기시험 합격자 발표", "응시자격 서류제출", "실기시험 원서접수", "실기시험", "최종 합격자 발표"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setRowHeight(60);
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1324, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("저장한 일정보기", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // 메인 화면의 로그인 버튼
        jFrame1.setLocation(200, 200);
        jFrame1.setSize(450, 300);
        jFrame1.setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
        // 회원가입 화면의 회원가입 버튼
        String id = txtJID.getText();          String name = txtName.getText();             String phone = txtPhone.getText();
        String pw = txtJPW.getText();       String checkPw = txtJCheckPW.getText();
        
        //아이디 중복 확인, 비밀번호 확인, 비밀번호 규칙 확인(특수문자 한개) 
        if(id.equals("") || name.equals("") || pw.equals("")) {
            JOptionPane.showMessageDialog(null, "정보를 입력해주세요.", null, JOptionPane.INFORMATION_MESSAGE);
        } else if(!checkResult.getText().equals("사용 가능한 아이디입니다.")) {
            JOptionPane.showMessageDialog(null, "아이디 중복을 확인해주세요.", null, JOptionPane.INFORMATION_MESSAGE);
        } else if(!checkPattern.getText().equals("사용 가능합니다.")) {
            JOptionPane.showMessageDialog(null, "비밀번호 규칙을 확인해주세요.", null, JOptionPane.INFORMATION_MESSAGE);
        } else if(!pw.equals(checkPw)) {
            JOptionPane.showMessageDialog(null, "비밀번호 확인이 일치하지 않습니다.", null, JOptionPane.INFORMATION_MESSAGE);
            txtJPW.setText("");
            txtJCheckPW.setText("");
        } else {
            String strSQL = "Insert Into [User] Values('" + id +"', '" + pw + "', '" + name + "', '" + phone + "')";
            try {   // DB에 추가
                DBM.dbOpen();
                DBM.DB_stmt.executeUpdate(strSQL);
                DBM.dbClose();
            } catch(Exception e) {
                e.printStackTrace();
            }
            txtJID.setText("");     txtName.setText("");        txtJPW.setText("");         txtJCheckPW.setText("");
            jFrame2.setVisible(false);
        }
    }//GEN-LAST:event_btnJoinActionPerformed

    private void btnIdCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdCheckActionPerformed
        // 회원가입 화면의 중복확인 버튼
        String checkID = txtJID.getText();
        String strSQL = "SELECT ID FROM [User] WHERE ID = '" + checkID + "'";
        try {
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            
            if(DBM.DB_rs.next()) {
                checkResult.setText("이미 존재하는 아이디입니다.");
                checkResult.setForeground(Color.red);
            } else {
                checkResult.setText("사용 가능한 아이디입니다.");
                checkResult.setForeground(Color.blue);
            }
            DBM.dbClose();
        } catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnIdCheckActionPerformed

    private void btnLJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLJoinActionPerformed
        // 로그인 화면의 회원가입 버튼
        jFrame2.setLocation(200, 200);
        jFrame2.setSize(665, 500);
        jFrame1.setVisible(false);
        jFrame2.setVisible(true);
    }//GEN-LAST:event_btnLJoinActionPerformed

    private void btnLLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLLoginActionPerformed
        // 로그인 화면의 로그인 버튼
        String ID = txtLID.getText();
        String pw = txtLPW.getText();
        String strSQL = "SELECT Password FROM [User] WHERE Id = '" +ID+"'" ;
        
        try {
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            
            //로그인 처리
            if(DBM.DB_rs.next()) {      //로그인 성공
                if(DBM.DB_rs.getString(1).equals(pw)) {
                    loginID = ID;
                    jFrame1.setVisible(false);
                    lblLoginCheck.setText(loginID+"님");
                    btnLogin.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(null, "아이디 또는 비밀번호가 틀립니다.", null, JOptionPane.INFORMATION_MESSAGE);
                    txtLID.setText(""); 
                    txtLPW.setText("");
                }
            } else {    //로그인 실패
                JOptionPane.showMessageDialog(null, "아이디 또는 비밀번호가 틀립니다.", null, JOptionPane.INFORMATION_MESSAGE);
                txtLID.setText(""); 
                txtLPW.setText("");
            }
            DBM.dbClose();
        } catch(Exception e) {
            e.printStackTrace();
        }         
    }//GEN-LAST:event_btnLLoginActionPerformed

    private void txtJIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJIDKeyTyped
        checkResult.setText("아이디 중복을 확인해주세요.");
        checkResult.setForeground(Color.blue);
    }//GEN-LAST:event_txtJIDKeyTyped

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(loginID == null) {   // 로그인하지 않은 상태에서는 사용 불가능
            JOptionPane.showMessageDialog(null, "로그인 후 사용할 수 있습니다.", null, JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        int selectRow = jTable1.getSelectedRow(), iCntRow = 0;
        
        if(selectRow < 0) {
            JOptionPane.showMessageDialog(null, "선택된 값이 없습니다.", null, JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        String selectDescription = jComboBox1.getSelectedItem().toString();
//        String selectDocregdt = jTable1.getValueAt(selectRow, 1).toString();
//        String selectDocExamdt = jTable1.getValueAt(selectRow, 2).toString();
//        String selectDocPassdt = jTable1.getValueAt(selectRow, 3).toString();
//        String selectDocument = jTable1.getValueAt(selectRow, 4).toString();
//        String selectPracregdt = jTable1.getValueAt(selectRow, 5).toString();
//        String selectPracexamdt = jTable1.getValueAt(selectRow, 6).toString();
//        String selectPracpassdt = jTable1.getValueAt(selectRow, 7).toString();
        
        for(int idx = 0; idx < jTable2.getRowCount(); idx++) {
            if(jTable2.getValueAt(idx, 0) == null) {
                iCntRow = idx;
                break;
            }
            if(jTable2.getValueAt(idx, 0).equals(selectDescription)) // 같은 행이 추가되지 않도록
                return;
        }
        
        jTable2.setValueAt(selectDescription, iCntRow, 0);
//        jTable2.setValueAt(selectDocregdt, iCntRow, 1);
//        jTable2.setValueAt(selectDocExamdt, iCntRow, 2);
//        jTable2.setValueAt(selectDocPassdt, iCntRow, 3);
//        jTable2.setValueAt(selectDocument, iCntRow, 4);
//        jTable2.setValueAt(selectPracregdt, iCntRow, 5);
//        jTable2.setValueAt(selectPracexamdt, iCntRow, 6);
//        jTable2.setValueAt(selectPracpassdt, iCntRow, 7);
        // jTable2에 현재 날짜에서 가장 가까운 시험 추가
        
        // DB에 INSERT 추가
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
      
        description.clear(); 
        
        docexamdt.clear();
        docpassdt.clear();
        docregenddt.clear();
        docregstartdt.clear();
        docsubmitentdt.clear();
        docsubmitstartdt.clear();
        pracexamenddt.clear();
        pracexamstartdt.clear();
        pracpassdt.clear();
        pracregenddt.clear();
        pracregstartdt.clear();
       
       
        Cdata api = new Cdata(); 
        
        String url = "";
         
        //api 요청 데이터 선택
        switch(jComboBox1.getSelectedIndex()){
            case 0 : //기능사
                url = "http://openapi.q-net.or.kr/api/service/rest/InquiryTestInformationNTQSVC/getCList";
                break;
            case 1: //기사, 산업 기사
                url = "http://openapi.q-net.or.kr/api/service/rest/InquiryTestInformationNTQSVC/getEList";
                break;
            case 2: // 기능장
                url = "http://openapi.q-net.or.kr/api/service/rest/InquiryTestInformationNTQSVC/getMCList";
                break;
            case 3: // 기술사
                url = "http://openapi.q-net.or.kr/api/service/rest/InquiryTestInformationNTQSVC/getPEList";
                break;
        }
        
       
        
            //받은 데이터 가공
            try {
               
                String apidata =  api.getdata(url);
                StringReader sr = new StringReader(apidata);
               
                JSONParser jp = new JSONParser();            
                Object obj = jp.parse(sr);
                 
                JSONObject jo = (JSONObject) obj;//jo는 제이슨이며 api 데이터가 저장되어있음
         
                //api json 구조 response - body - itemes - item
                JSONObject parse_response = (JSONObject) jo.get("response");
                JSONObject parse_body = (JSONObject) parse_response.get("body");   
                JSONObject items = (JSONObject) parse_body.get("items");
       
                JSONArray item = (JSONArray) items.get("item");
                
       
                 
                // for(int i = 0 ; i < item.size() ; i++){//데이터 4개 이상 시 예외처리 필요
                int j=0;
                if(item.size() > 4){
                    j = 4;
                }else{
                    j = item.size();
                }
                for(int i = 0 ; i < j ; i++){   
                    JSONObject object = (JSONObject) item.get(i);
                    
                    description.add(object.get("description"));
                    docexamdt.add(object.get("docexamdt"));
                    docpassdt.add(object.get("docpassdt"));
                    docregenddt.add(object.get("docregenddt"));
                    docregstartdt.add(object.get("docregstartdt"));
                    docsubmitentdt.add(object.get("docsubmitentdt"));
                    docsubmitstartdt.add(object.get("docsubmitstartdt"));
                    pracexamenddt.add(object.get("pracexamenddt"));
                    pracexamstartdt.add(object.get("pracexamstartdt"));
                    pracpassdt.add(object.get("pracpassdt"));
                    pracregenddt.add(object.get("pracregenddt"));
                    pracregstartdt.add(object.get("pracregstartdt"));
                }
             
            } catch (Exception ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
       
            
            
            // 가공한 데이터 테이블에 삽입
            switch(jComboBox1.getSelectedIndex()){ 
            case 0 : //기능사
                    for(int i = 0 ; i<description.size() ; i++){
                    String cc = description.get(i).toString();
                    if(cc.contains("상시")){
                        continue;
                    }
              
                    jTable1.setValueAt(description.get(i) , i, 0);//회차      
                    jTable1.setValueAt(docregstartdt.get(i)+"~"+docregenddt.get(i), i, 1);//필기 원서접수 시작~끝
                    jTable1.setValueAt(docexamdt.get(i), i, 2);//필기시험일
                    jTable1.setValueAt(docpassdt.get(i), i, 3);//합격자발표일
    
                    //기능사는 서류 제출이 없음
                    jTable1.setValueAt("별도의 서류제출 없음", i, 4);
                    jTable1.setValueAt(pracregstartdt.get(i)+"~"+pracregenddt.get(i), i, 5);//실기 원서 접수 시간~끝
                    jTable1.setValueAt(pracexamstartdt.get(i)+"~"+pracexamenddt.get(i), i, 6);//실기 시험일
                    jTable1.setValueAt(pracpassdt.get(i), i, 7);//최종 합격자 팔표일
                    }
                    break;
            
            case 1: //기사, 산업 기사
                
                    for(int i = 0 ; i<description.size() ; i++){   
                    jTable1.setValueAt(description.get(i) , i, 0);//회차      
                    jTable1.setValueAt(docregstartdt.get(i)+"~"+docregenddt.get(i), i, 1);//필기 원서접수 시작~끝
                    jTable1.setValueAt(docexamdt.get(i), i, 2);//필기시험일
                    jTable1.setValueAt(docpassdt.get(i), i, 3);//합격자발표일
                    jTable1.setValueAt(docsubmitstartdt.get(i)+"~"+docsubmitentdt.get(i), i, 4);//서류제출기간 시작~끝
                    jTable1.setValueAt(pracregstartdt.get(i)+"~"+pracregenddt.get(i), i, 5);//실기 원서 접수 시간~끝
                    jTable1.setValueAt(pracexamstartdt.get(i)+"~"+pracexamenddt.get(i), i, 6);//실기 시험일
                    jTable1.setValueAt(pracpassdt.get(i), i, 7);//최종 합격자 팔표일
                    }
                    break;
                    
            case 2: // 기능장
                    for(int i = 0 ; i<description.size() ; i++){   
                    jTable1.setValueAt(description.get(i) , i, 0);//회차      
                    jTable1.setValueAt(docregstartdt.get(i)+"~"+docregenddt.get(i), i, 1);//필기 원서접수 시작~끝
                    jTable1.setValueAt(docexamdt.get(i), i, 2);//필기시험일
                    jTable1.setValueAt(docpassdt.get(i), i, 3);//합격자발표일
                    jTable1.setValueAt(docsubmitstartdt.get(i)+"~"+docsubmitentdt.get(i), i, 4);//서류제출기간 시작~끝
                    jTable1.setValueAt(pracregstartdt.get(i)+"~"+pracregenddt.get(i), i, 5);//실기 원서 접수 시간~끝
                    jTable1.setValueAt(pracexamstartdt.get(i)+"~"+pracexamenddt.get(i), i, 6);//실기 시험일
                    jTable1.setValueAt(pracpassdt.get(i), i, 7);//최종 합격자 팔표일
                    }
                    break;
            case 3: // 기술사
                    for(int i = 0 ; i<description.size() ; i++){   
                    jTable1.setValueAt(description.get(i) , i, 0);//회차      
                    jTable1.setValueAt(docregstartdt.get(i)+"~"+docregenddt.get(i), i, 1);//필기 원서접수 시작~끝
                    jTable1.setValueAt(docexamdt.get(i), i, 2);//필기시험일
                    jTable1.setValueAt(docpassdt.get(i), i, 3);//합격자발표일
                    jTable1.setValueAt(docsubmitstartdt.get(i)+"~"+docsubmitentdt.get(i), i, 4);//서류제출기간 시작~끝
                    jTable1.setValueAt(pracregstartdt.get(i)+"~"+pracregenddt.get(i), i, 5);//실기 원서 접수 시간~끝
                    jTable1.setValueAt(pracexamstartdt.get(i)+"~"+pracexamenddt.get(i), i, 6);//실기 시험일
                    jTable1.setValueAt(pracpassdt.get(i), i, 7);//최종 합격자 팔표일
                    }
                    break;
            }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtJPWKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJPWKeyTyped
        // 비밀번호 규칙 확인
        String checkPW = txtJPW.getText()+evt.getKeyChar();
        
        if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE)
            checkPW = txtJPW.getText();
        
        Matcher match;
        Pattern pattern = Pattern.compile("^(?=.*[A-Za-z])(?=.*\\d)(?=.*[$@$!%*#?&])[A-Za-z\\d$@$!%*#?&]{8,}$");
        
        match = pattern.matcher(checkPW);
        if(match.find()) {
            checkPattern.setText("사용 가능합니다.");
        } else {
            checkPattern.setText("영문 소문자, 숫자, 특수문자 조합, 최소 8자리");
        }
    }//GEN-LAST:event_txtJPWKeyTyped

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectRow = jTable2.getSelectedRow();
        
        if(selectRow < 0) {
            JOptionPane.showMessageDialog(null, "선택된 값이 없습니다.", null, JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        for(int idx=0; idx<jTable1.getColumnCount(); idx++)
            jTable2.setValueAt(null, selectRow, idx);
        
        // DB에 DELETE 추가
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // 로그인 전에 저장한 일정 탭에 접근할 수 없게
        int selectIndex = jTabbedPane1.getSelectedIndex();
        String tabTitle = jTabbedPane1.getTitleAt(selectIndex);
        
        if(tabTitle.equals("저장한 일정보기") && loginID == null) {
            JOptionPane.showMessageDialog(null, "로그인 후 접근 가능합니다.", null, JOptionPane.INFORMATION_MESSAGE);
            jTabbedPane1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnIdCheck;
    private javax.swing.JButton btnJoin;
    private javax.swing.JButton btnLJoin;
    private javax.swing.JButton btnLLogin;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel checkPattern;
    private javax.swing.JLabel checkResult;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLoginCheck;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPw;
    private javax.swing.JLabel lblPwCheck;
    private javax.swing.JPasswordField txtJCheckPW;
    private javax.swing.JTextField txtJID;
    private javax.swing.JPasswordField txtJPW;
    private javax.swing.JTextField txtLID;
    private javax.swing.JPasswordField txtLPW;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
